name: Build and Deploy
env:
  CI: false
  GITHUB_USERNAME: ${{ github.repository_owner }}
  REACT_APP_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This is automatically set by Github Actions
  USE_GITHUB_DATA: "true"
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
  schedule:
    - cron: "0 12 * * 1"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
        env: 
          ACCESS_TOKEN: '${{secrets.MY_GITHUB_PAGES_ACCESS_TOKEN}}'

      - name: update npm
        run: |
          npm install npm@latest -g

      - name: Install and Build 🔧 # Build the Project
        run: |
          npm install --force
          npm run build -- force

      - name: Predeploy 🔧🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_PAGES_ACCESS_TOKEN }} # This is provided by GitHub.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.

      - name: Deploy 🚀
        run: |
          git config --global user.email "fazouz2010@gmail.com"
          git config --global user.name "Github Actions"
          git config --global credential.helper cache
          git clone -b gh-pages https://${{secrets.MY_GITHUB_PAGES_ACCESS_TOKEN}}@github.com/Azooz2014/Portfolio.git
          git remote add githubPages https://${{secrets.MY_GITHUB_PAGES_ACCESS_TOKEN}}@github.com/Azooz2014/Azooz2014.github.io.git
          git checkout -b gh-pages
          git push --force githubPages gh-pages:master

      - name: Archive npm failure logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: npm-logs
          path: ~/.npm/_logs
